### ISSUE TITLE
Does this mod effect vanilla world generation? 

### ISSUE THREAD

**Issue by MediaSavvy** [ItzjustElias/FastMathMod#2]
Does this mod simply optimize Minecrafts math with no other side effects to vanilla world generation? Or does it also slighty change vanilla world generation behaviour?

I apologize if this is not the correct place for this question.

**Comment by ItzjustElias** [comment]
No worries, the mod only changes the cos and sin with the use of mixins, so it should have no real effect on the world generation itself. If you encounter any issues or errors, you're welcome to share!
