### ISSUE TITLE
Question: Does mod alter game math at all or purely speed up math?

### ISSUE THREAD

**Issue by Firebolt360** [ItzjustElias/FastMathMod#4]
With this mod, would anything change with the game logic/calculations in a way that differs from vanilla in terms of RNG or anything else that could be affected by this mod? Or does this mod only speed up the existing vanilla calculations?

**Comment by Firebolt360** [comment]
For example, mob behavior changing ever so slightly behind the scenes with this mod. Would that be a concern at all for anyone looking to maintain vanilla parity?

**Comment by ItzjustElias** [comment]
Normally, not no, it should only change the way it calculates. It should not change any formulas or RNG or mobs behavior.
